from sqlalchemy import (
    Boolean,
    Column,
    Date,
    DateTime,
    Float,
    Integer,
    MetaData,
    Table,
)

metadata = MetaData()

bike_rentals_raw = Table(
    "bike_rentals_raw",
    metadata,
    Column("instant", Integer, primary_key=True),
    Column("date", Date, nullable=False),
    Column("season", Integer, nullable=False),
    Column("year", Integer, nullable=False),
    Column("month", Integer, nullable=False),
    Column("hour", Integer, nullable=False),
    Column("holiday", Integer, nullable=False),
    Column("weekday", Integer, nullable=False),
    Column("working_day", Integer, nullable=False),
    Column("weather_situation", Integer, nullable=False),
    Column("temperature", Float, nullable=False),
    Column("apparent_temperature", Float, nullable=False),
    Column("humidity", Float, nullable=False),
    Column("wind_speed", Float, nullable=False),
    Column("casual_rentals", Integer, nullable=False),
    Column("registered_rentals", Integer, nullable=False),
    Column("total_rentals", Integer, nullable=False),
)

bike_rentals_features = Table(
    "bike_rentals_features",
    metadata,
    Column("instant", Integer, primary_key=True),
    Column("timestamp", DateTime, nullable=False, unique=True),
    Column("year", Integer, nullable=False),
    Column("month", Integer, nullable=False),
    Column("day", Integer, nullable=False),
    Column("hour", Integer, nullable=False),
    Column("weekday", Integer, nullable=False),
    Column("is_weekend", Boolean, nullable=False),
    Column("season", Integer, nullable=False),
    Column("holiday", Integer, nullable=False),
    Column("working_day", Integer, nullable=False),
    Column("weather_situation", Integer, nullable=False),
    Column("temperature", Float, nullable=False),
    Column("apparent_temperature", Float, nullable=False),
    Column("humidity", Float, nullable=False),
    Column("wind_speed", Float, nullable=False),
    Column("hour_sin", Float, nullable=False),
    Column("hour_cos", Float, nullable=False),
    Column("weekday_sin", Float, nullable=False),
    Column("weekday_cos", Float, nullable=False),
    Column("month_sin", Float, nullable=False),
    Column("month_cos", Float, nullable=False),
    Column("total_rentals", Integer, nullable=False),
)