project:
  type: website
  output-dir: docs

website:
  title: "Engenharia dos Fluxos"
  description: "Explorando sistemas complexos através do Python"
  google-analytics: "G-H2WW8TV4X8"
  
  site-url: https://danicarvalhomf.github.io/python-especialista/
  repo-url: https://github.com/danicarvalhomf/python-especialista

  open-graph: true
  twitter-card: true

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: posts.qmd
        text: Artigos
  
      - href: about.qmd
        text: Sobre

format:
  html:
    theme:
      #- cosmo
      #- brand
      light: litera
      dark: darkly
    css: styles.css
    toc: true


execute:
  freeze: auto
